#!/bin/bash -e
##-------------------------------------------------------------------
## File: check_proc_mem.sh
##-------------------------------------------------------------------
if [ "$1" = "-w" ] && [ "$2" -gt "0" ] && \
    [ "$3" = "-c" ] && [ "$4" -gt "0" ]; then
    pidPattern=${5?"specify how to get pid"}

    if [ "$pidPattern" = "--pidfile" ]; then
        pidfile=${6?"pidfile to get pid"}
        pid=$(cat $pidfile)
    elif [ "$pidPattern" = "--cmdpattern" ]; then
        cmdpattern=${6?"command line pattern to find out pid"}
        pid=$(ps -ef | grep "$cmdpattern" | grep -v grep | grep -v check_proc_mem | head -n 1 | awk -F' ' '{print $2}')
    elif [ "$pidPattern" = "--pid" ]; then
        pid=${6?"pid"}
    else
        echo "ERROR input for pidpattern"
        exit 1
    fi

    memUsage=`ps -p $pid -o %mem | tail -n 1 | sed -e 's/^[ \t]*//'`
    #echo "OK MEM used by process($pid) is $memUsage %|MEM=$memUsage"
    echo "RAM usage by process ($pid): $memUsage %"
fi
## File - check_proc_mem.sh ends
